# Generated by Django 3.1.4 on 2021-01-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comments_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=40)),
            ],
        ),
    ]
