# Generated by Django 3.1.4 on 2021-01-13 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='item_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Listing', to='auctions.listing'),
        ),
    ]
