# Generated by Django 3.1.4 on 2021-01-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210113_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
