# Generated by Django 3.1.4 on 2021-01-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210113_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchlist_item',
            new_name='watchlist',
        ),
    ]
