# Generated by Django 3.1.4 on 2021-01-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210120_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('listings', models.ManyToManyField(blank=True, related_name='categories', to='auctions.Listing')),
            ],
        ),
    ]
