# Generated by Django 3.1.4 on 2021-01-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20210127_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='winner',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
