# Generated by Django 3.1.4 on 2021-01-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_winner_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
