# Generated by Django 3.1.4 on 2021-01-29 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
